import Head from "next/head";
import Link from "next/link";
import NavBar from "../navBar";
import BtnSignOut from "./btnSignOut";
import styles from "../../styles/AuthorizeUser.module.css";

export default function AuthorizeUser() {
  return (
    <section className="overflow-hidden">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavBar />
      <div className="details">
        <h5 className="py-1 mx-6"></h5>
      </div>
      <div className={styles.container}>
        <h1
          className={`text-5xl pt-24 font-extrabold text-transparent bg-clip-text bg-gradient-to-br from-pink-400 to-red-600 ${styles.animate_text}`}
        >
          Welcome to our website....
          <span className={styles.space}>&#160;</span>
        </h1>
      </div>
      <div className="content">
        <h3>
          <div className={`pt-24 ${styles.wrap}`}>
            <Link href={"/profile"}>
              <button
                type="button"
                className={`pt-20 ${styles.profile_button}`}
              >
                <span>Profile Page</span>
              </button>
            </Link>
          </div>
        </h3>
      </div>
    </section>
  );
}
